-- Fase 1: Mejorar el Módulo de RRHH
-- Modificar la tabla de Cuentas y crear la tabla de documentos.

-- 1. Añadir columnas a la tabla existente "Cuentas"
ALTER TABLE public."Cuentas"
ADD COLUMN fecha_expiracion_contrato DATE,
ADD COLUMN duracion_contrato TEXT;

-- 2. Crear nueva tabla para el repositorio de documentos
CREATE TABLE public.documentos_empleados (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public."Cuentas"(user_id) ON DELETE CASCADE,
    nombre_documento TEXT NOT NULL,
    tipo_documento TEXT, -- E.g., 'Contrato', 'Identificación', 'CV', etc.
    path_almacenamiento TEXT NOT NULL UNIQUE, -- Ruta en Supabase Storage
    subido_en TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL,
    tamano_archivo INT, -- Tamaño en bytes
    tipo_mime TEXT -- E.g., 'application/pdf', 'image/png'
);

-- Añadir comentarios para claridad
COMMENT ON TABLE public.documentos_empleados IS 'Almacena los documentos asociados a cada empleado.';
COMMENT ON COLUMN public.documentos_empleados.user_id IS 'El empleado al que pertenece el documento.';
COMMENT ON COLUMN public.documentos_empleados.path_almacenamiento IS 'La ruta única del archivo en Supabase Storage.';

-- 3. Activar Row Level Security (RLS) en la nueva tabla
ALTER TABLE public.documentos_empleados ENABLE ROW LEVEL SECURITY;

-- Aquí se podrían añadir políticas de seguridad, pero se hará más adelante.
-- Ejemplo de política: CREATE POLICY "Los empleados pueden ver sus propios documentos" ON public.documentos_empleados FOR SELECT USING (auth.uid() = user_id);
